[package]
name = "ashell"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/pop-os/iced", features = ["tokio", "wayland", "advanced"] }
chrono = "0.4.31"
hyprland = "0.3.12"
serde = "1.0.190"
serde_json = "1.0.107"
sysinfo = "0.29.10"
tokio = { version = "1", features = ["full"] }
