[package]
name = "ashell"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/pop-os/iced", tag = "v0.10", features = ["tokio", "wayland", "advanced"] }
chrono = "0.4.31"
hyprland = "0.3.12"
serde = "1.0.190"
serde_json = "1.0.107"
sysinfo = "0.29.10"
tokio = { version = "1", features = ["full"] }
zbus = "3.14.1"
libpulse-binding = {version = "2.28.1", features = ["pa_v15"] }
libpulse-tokio = "0.1"
