[package]
name = "ashell"
version = "0.1.0"
edition = "2021"

[dependencies]
futures = "0.3.28"
futures-signals = "0.3.33"
glib = "0.18.2"
gtk4 = "0.7.3"
tokio = { version = "1", features = ["full"] }
