[package]
name = "ashell"
version = "0.1.0"
edition = "2021"

[dependencies.iced]
git = "https://github.com/pop-os/iced"
rev="296b32267d5b7d8f16a1efcef249931694fcd19e"
default-features = false 
features = ["tokio", "wayland", "advanced", "wgpu"] 

[dependencies]
chrono = "0.4"
hyprland = { git = "https://github.com/MalpenZibo/hyprland-rs", branch="master" }
serde = "1.0"
serde_json = "1.0"
sysinfo = "0.30"
tokio = { version = "1", features = ["full"] }
zbus = "4.2"
libpulse-binding = { version = "2.28", features = ["pa_v15"] }
libpulse-tokio = "0.1"
inotify = "0.10"
log = { version = "0.4", features=["serde"] }
flexi_logger = "0.28"
serde_yaml = "0.9"
nix = { version = "0.26.4", features = ["fs"] }
pipewire = "0.8.0"
wayland-client = "0.31.3"
wayland-protocols = { version = "0.32.1", features = ["client", "unstable"] }
itertools = "0.13.0"
hex_color = { version = "3.0.0", features = ["serde"] }

