[package]
name = "ashell"
version = "0.1.0"
edition = "2021"

[dependencies]
iced = { git = "https://github.com/pop-os/iced", rev="6115280d5277c50b8539d4eff6ab61050c51b592", features = ["tokio", "wayland", "advanced"] }
chrono = "0.4"
hyprland = "0.3"
serde = "1.0"
serde_json = "1.0"
sysinfo = "0.29"
tokio = { version = "1", features = ["full"] }
zbus = "3"
libpulse-binding = { version = "2.28", features = ["pa_v15"] }
libpulse-tokio = "0.1"
inotify = "0.10"
log = { version = "0.4", features=["serde"] }
flexi_logger = "0.27"
serde_yaml = "0.9"
log-panics = "2"
